version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'devjiwonchoi'
    groups:
      prod:
        dependency-type: 'production'
      dev:
        dependency-type: 'development'